float_objects = saxpy.o sscal.o scopy.o sswap.o sdot.o snrm2.o sasum.o isamax.o srotg.o srot.o 
double_objects = daxpy.o dscal.o dcopy.o dswap.o ddot.o dnrm2.o dasum.o idamax.o drotg.o drot.o 
complex_objects = caxpy.o cscal.o ccopy.o cswap.o cdotu.o cdotc.o scasum.o icamax.o crotg.o crot.o csrot.o
double_complex_objects = zaxpy.o zscal.o zcopy.o zswap.o zdotu.o dznrm2.o dzasum.o izamax.o zrotg.o zrot.o zdrot.o
other_objects = 
objects = $(float_objects) $(double_objects) $(complex_objects) $(double_complex_objects) $(other_objects)


all: $(objects) 
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -shared -o $(BIN_DIR)matrix-c.so $(addprefix $(BUILD_DIR),$(objects))

saxpy.o: 
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)saxpy.o -c $(SRC_DIR)saxpy.c

daxpy.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)daxpy.o -c $(SRC_DIR)daxpy.c

caxpy.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)caxpy.o -c $(SRC_DIR)caxpy.c

zaxpy.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)zaxpy.o -c $(SRC_DIR)zaxpy.c

sscal.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)sscal.o -c $(SRC_DIR)sscal.c

dscal.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)dscal.o -c $(SRC_DIR)dscal.c

cscal.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)cscal.o -c $(SRC_DIR)cscal.c

zscal.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)zscal.o -c $(SRC_DIR)zscal.c

scopy.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)scopy.o -c $(SRC_DIR)scopy.c

dcopy.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)dcopy.o -c $(SRC_DIR)dcopy.c

ccopy.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)ccopy.o -c $(SRC_DIR)ccopy.c

zcopy.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)zcopy.o -c $(SRC_DIR)zcopy.c

sswap.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)sswap.o -c $(SRC_DIR)sswap.c

dswap.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)dswap.o -c $(SRC_DIR)dswap.c

cswap.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)cswap.o -c $(SRC_DIR)cswap.c

zswap.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)zswap.o -c $(SRC_DIR)zswap.c

sdot.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)sdot.o -c $(SRC_DIR)sdot.c

ddot.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)ddot.o -c $(SRC_DIR)ddot.c

cdotu.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)cdotu.o -c $(SRC_DIR)cdotu.c

zdotu.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)zdotu.o -c $(SRC_DIR)zdotu.c

cdotc.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)cdotc.o -c $(SRC_DIR)cdotc.c

zdotc.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)zdotc.o -c $(SRC_DIR)zdotc.c

sasum.o: 
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)sasum.o -c $(SRC_DIR)sasum.c

dasum.o: 
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)dasum.o -c $(SRC_DIR)dasum.c

scasum.o: 
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)scasum.o -c $(SRC_DIR)scasum.c 

dzasum.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)dzasum.o -c $(SRC_DIR)dzasum.c

isamax.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)isamax.o -c $(SRC_DIR)isamax.c

idamax.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)idamax.o -c $(SRC_DIR)idamax.c

icamax.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)icamax.o -c $(SRC_DIR)icamax.c

izamax.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)izamax.o -c $(SRC_DIR)izamax.c

srotg.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)srotg.o -c $(SRC_DIR)srotg.c

drotg.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)drotg.o -c $(SRC_DIR)drotg.c

crotg.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)crotg.o -c $(SRC_DIR)crotg.c

zrotg.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)zrotg.o -c $(SRC_DIR)zrotg.c

srot.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)srot.o -c $(SRC_DIR)srot.c

drot.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)drot.o -c $(SRC_DIR)drot.c

crot.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)crot.o -c $(SRC_DIR)crot.c

zrot.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)zrot.o -c $(SRC_DIR)zrot.c

csrot.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)csrot.o -c $(SRC_DIR)csrot.c

zdrot.o:
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $(BUILD_DIR)zdrot.o -c $(SRC_DIR)zdrot.c


clean:
	rm -f $(BIN_DIR)*
	rm -f $(BUILD_DIR)*
